In [1]:
with open('open_write.txt','w') as file:
    file.write("This is sample file\ng")
print("File created succesfully")

File created succesfully

In [4]:
with open('example.txt','w') as file:
    for i in range(0,6):
        file.write(f"This is statement number{i}")
print('File created succesfully.....')

File created succesfully.....

In [5]:
with open('example.txt','r') as file:
    data=file.read()
print(data)

This is statement number0This is statement number1This is statement number2This is statement number3This is statement number4This is statement number5

In [6]:
lines=['This is first line',
       'This is first line',
'This is first line','This is first line']

with open('multi.txt','w') as file:
    for li in lines:
        file.write(li + '\n')
print('Fike Created succesfully')

Fike Created succesfully

In [8]:
with open('multi.txt','r') as file:
     lines=file.readlines()
     for t in lines:
         print(t.strip(),'\n')

This is first line

This is first line

This is first line

This is first line

In [9]:
import pandas as pd
data = {
    'Employee ID': ['EMP101', 'EMP102', 'EMP103', 'EMP104', 'EMP105', 'EMP106', 'EMP107', 'EMP108'],
    'Name': ['Aarav Sharma', 'Priya Nair', 'Rohan Verma', 'Ananya Iyer', 'Vikram Patel', 'Sneha Kulkarni', 'Kabir Das', 'Pooja Rao'],
    'Department': ['Engineering', 'Human Resources', 'Sales', 'Finance', 'Marketing', 'Engineering', 'Operations', 'Customer Support'],
    'Designation': ['Software Engineer', 'HR Manager', 'Sales Executive', 'Accountant', 'Digital Marketer', 'QA Lead', 'Operations Analyst', 'Support Lead'],
    'Joining Date': ['2022-03-15', '2021-07-10', '2023-01-20', '2022-11-05', '2023-06-12', '2020-09-18', '2023-04-25', '2021-12-01'],
    'Salary (INR/Year)': [950000, 1120000, 600000, 750000, 680000, 1250000, 550000, 580000],
    'Email': ['aarav.sharma@example.com', 'priya.nair@example.com', 'rohan.verma@example.com', 'ananya.iyer@example.com', 'vikram.patel@example.com', 'sneha.kulkarni@example.com', 'kabir.das@example.com', 'pooja.rao@example.com']
}
data

{'Employee ID': ['EMP101',
  'EMP102',
  'EMP103',
  'EMP104',
  'EMP105',
  'EMP106',
  'EMP107',
  'EMP108'],
 'Name': ['Aarav Sharma',
  'Priya Nair',
  'Rohan Verma',
  'Ananya Iyer',
  'Vikram Patel',
  'Sneha Kulkarni',
  'Kabir Das',
  'Pooja Rao'],
 'Department': ['Engineering',
  'Human Resources',
  'Sales',
  'Finance',
  'Marketing',
  'Engineering',
  'Operations',
  'Customer Support'],
 'Designation': ['Software Engineer',
  'HR Manager',
  'Sales Executive',
  'Accountant',
  'Digital Marketer',
  'QA Lead',
  'Operations Analyst',
  'Support Lead'],
 'Joining Date': ['2022-03-15',
  '2021-07-10',
  '2023-01-20',
  '2022-11-05',
  '2023-06-12',
  '2020-09-18',
  '2023-04-25',
  '2021-12-01'],
 'Salary (INR/Year)': [950000,
  1120000,
  600000,
  750000,
  680000,
  1250000,
  550000,
  580000],
 'Email': ['aarav.sharma@example.com',
  'priya.nair@example.com',
  'rohan.verma@example.com',
  'ananya.iyer@example.com',
  'vikram.patel@example.com',
  'sneha.kulkarni@example.com',
  'kabir.das@example.com',
  'pooja.rao@example.com']}

In [10]:
df=pd.DataFrame(data)
df

,Employee ID,Name,Department,Designation,Joining Date,Salary (INR/Year),Email
0,EMP101,Aarav Sharma,Engineering,Software Engineer,2022-03-15,950000,aarav.sharma@example.com
1,EMP102,Priya Nair,Human Resources,HR Manager,2021-07-10,1120000,priya.nair@example.com
2,EMP103,Rohan Verma,Sales,Sales Executive,2023-01-20,600000,rohan.verma@example.com
3,EMP104,Ananya Iyer,Finance,Accountant,2022-11-05,750000,ananya.iyer@example.com
4,EMP105,Vikram Patel,Marketing,Digital Marketer,2023-06-12,680000,vikram.patel@example.com
5,EMP106,Sneha Kulkarni,Engineering,QA Lead,2020-09-18,1250000,sneha.kulkarni@example.com
6,EMP107,Kabir Das,Operations,Operations Analyst,2023-04-25,550000,kabir.das@example.com
7,EMP108,Pooja Rao,Customer Support,Support Lead,2021-12-01,580000,pooja.rao@example.com

In [11]:
df.to_csv('exapmle_tab.tsv',sep='\t',index=False)

In [12]:
df_read=pd.read_csv('exapmle_tab.tsv',sep='\t')
df_read.head()

,Employee ID,Name,Department,Designation,Joining Date,Salary (INR/Year),Email
0,EMP101,Aarav Sharma,Engineering,Software Engineer,2022-03-15,950000,aarav.sharma@example.com
1,EMP102,Priya Nair,Human Resources,HR Manager,2021-07-10,1120000,priya.nair@example.com
2,EMP103,Rohan Verma,Sales,Sales Executive,2023-01-20,600000,rohan.verma@example.com
3,EMP104,Ananya Iyer,Finance,Accountant,2022-11-05,750000,ananya.iyer@example.com
4,EMP105,Vikram Patel,Marketing,Digital Marketer,2023-06-12,680000,vikram.patel@example.com